### ISSUE TITLE
Plugin outputs unreadable/unintelligible YAML for Deployments and other workloads  

### ISSUE THREAD

**Issue by alianjo** [alianjo/saver#1]
**Description:**  
When using the `kubectl save` command to export a workload (e.g., Deployment, StatefulSet, DaemonSet), the output YAML is heavily unreadable and cluttered with unnecessary fields. This makes it very difficult to use the exported YAML for practical purposes, such as backup or redeployment.  

**Steps to Reproduce:**  
1. Run the following command:  
   ```bash  
   kubectl save deployment --namespace controller -o controller-deployments.yaml  
   ```  
2. Examine the content of the output file.  

**Actual Output:**  
The output YAML contains a large amount of irrelevant or redundant metadata, such as `managedFields`, `annotations`, and encoded `raw` field data. Example output:  
```yaml  
typemeta:  
  kind: ""  
  apiversion: ""  
objectmeta:  
  name: controller  
  namespace: controller  
  labels:  
    app: controller  
  annotations:  
    deployment.kubernetes.io/revision: "1"  
  managedfields:  
    - manager: kubectl-client-side-apply  
      operation: Update  
      fieldsv1:  
        raw:  
        - 123  
        - 34  
        # ...and so on  
```  
These details make the output YAML almost unusable for manual editing or redeployment.  

**Expected Output:**  
The saved YAML should be clean, containing only essential fields necessary to recreate the resource. For example:  
```yaml  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: controller  
  namespace: controller  
  labels:  
    app: controller  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: controller  
  template:  
    metadata:  
      labels:  
        app: controller  
    spec:  
      containers:  
      - name: generichttppopulator  
        image: registry.greenplus.cloud/cache/viveksinghggits/generichttppopulator:0.1.0  
        args:  
        - --mode=controller  
```  

**Impact:**  
This issue significantly reduces the plugin's usefulness for practical purposes, such as creating backups or migrating workloads, as users must manually clean up the exported YAML.
